### ISSUE TITLE
I frickin' love this

### ISSUE THREAD

**Issue by philthepill** [adamb924/UnicodeInput#2]
Hi
I really really really appreciate your tool.
I write academic papers in philosophy/logic and it comes in handy! It's super practical.
Could you make it a third as big and add a toggle to make it "floating" constantly above all windows?
Sort of a "mini floating mode".
Greetings from Switzerland Europe.
Phil

**Comment by adamb924** [comment]
Hey, thanks for your kind words. It's probably the most useful software
I've created, so I'm happy other people are using it too.

Those are good suggestions. Unfortunately I don't have a lot of time to
work on it these days.

Thanks,
Adam

**Comment by adamb924** [comment]
I was adding features and revising the code, so I went ahead and implemented some of these changes.

- With the “Options” button you can now hide the codepoint view, which will make it smaller.
- With the “Options” button you can choose to keep the window always on top.
- Also it will remember the position of the window now.
